export const FETCH_GROUP_REQUEST = "FETCH_GROUP_REQUEST";
export const FETCH_GROUP_SUCCESS = "FETCH_GROUP_SUCCESS";
export const FETCH_GROUP_FAILURE = "FETCH_GROUP_FAILURE";

//share
export const ADD_SHARE_REQUEST = "ADD_SHARE_REQUEST";
export const ADD_SHARE_SUCCESS = "ADD_SHARE_SUCCESS";
export const ADD_SHARE_FAILURE = "ADD_SHARE_FAILURE";
export const EDIT_SHARE_REQUEST = "EDIT_SHARE_REQUEST";
export const EDIT_SHARE_SUCCESS = "EDIT_SHARE_SUCCESS";
export const EDIT_SHARE_FAILURE = "EDIT_SHARE_FAILURE";
export const DELETE_SHARE_REQUEST = "DELETE_SHARE_REQUEST";
export const DELETE_SHARE_SUCCESS = "DELETE_SHARE_SUCCESS";
export const DELETE_SHARE_FAILURE = "DELETE_SHARE_FAILURE";

//group
export const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAILURE = "ADD_GROUP_FAILURE";
export const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_FAILURE = "DELETE_GROUP_FAILURE";

//user
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

//settle
export const SIMPLIFY_REQUEST = "SIMPLIFY_REQUEST";
export const SIMPLIFY_SUCCESS = "SIMPLIFY_SUCCESS";
export const SIMPLIFY_FAILURE = "SIMPLIFY_FAILURE";
