export const FETCH_GROUP_REQUEST = "FETCH_GROUP_REQUEST";
export const FETCH_GROUP_SUCCESS = "FETCH_GROUP_SUCCESS";
export const FETCH_GROUP_FAILURE = "FETCH_GROUP_FAILURE";
export const ADD_SHARE_REQUEST = "ADD_SHARE_REQUEST";
export const ADD_SHARE_SUCCESS = "ADD_SHARE_SUCCESS";
export const ADD_SHARE_FAILURE = "ADD_SHARE_FAILURE";
